# Generated by Django 5.2.7 on 2025-10-30 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date'], 'verbose_name': 'Liveact'},
        ),
    ]
